### ISSUE TITLE
re-structuring experimental design and results

### ISSUE THREAD

**Issue by dicook** [nspyrison/spinifex_study#3]
- A short overview should begin section 3.
- Next section describes the factor (vis type), and the blocking factors. A simple plot illustrating each would be helpful, like fig 5 for var-cov, which would be shifted in to this section. the vis type should have the biplot of pc1 v pc2, a tour projection, and a radial projection where variable is fully extended (length 1) and axis coloured specially. the location should show density plots of the two clusters being compared (not the other clusters) as a single variable (0-1), and a 33/67 combination and as a 50/50 combination, where the axis is labelled with the projection producing that combination
- Section stating the main hypothesis that the radial tour should have higher performance in accuracy and speed
- Separate section on the data simulation
- Section on data collection, including the ordering of presentation to subjects (fig 6), maybe separate subjections for explaining the permuted delivery, and the randomisation, separate subsection on the tasks and the questions asked of subjects. 
- Demographics of the collected sample (fig 7) should go in an appendix, along with more details of app including screen shots.
- Figures 8, 10 should be in appendix.
- can you make the collected data available to me? (./apps_supplementary/v4_prolifico_100/_analysis.rmd)

**Comment by nspyrison** [comment]
> - Section stating the main hypothesis that the radial tour should have higher performance in accuracy and speed

This is discussed in 3.1 Objective, Paragraph 3. I will move them higher in the section to give them more emphasis. Given the user interaction, the number of variables, and relatively small change in the basis, Radial doesn't and shouldn't perform faster than Grand tour, but does and should perform with higher accuracy. 

> - can you make the collected data available to me? (./apps_supplementary/v4_prolifico_100/_analysis.rmd)

3x .rds files are on the repo in ./apps_supplementary/v4_prolifico_100/v4_prolifico_100/data/ starting from raw_prolific_100.rds, I have added your and Kim's Monash accounts to the sheet directly, so should be able to auth through a direct API pull if you like.
